name: build

on:
  [push, pull_request]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -t lyra-build-env
